### ISSUE TITLE
Consideration of OGC document relations

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#22]
1. https://www.w3.org/TR/prov-o/ defines a relation called `wasInfluencedBy` which is being used in OGC. Should we have this?

2. "Uses": OGC uses the "uses" relation to indicate a document "refers" to another document. Should we have a "refers" relationship?

3. "IsProfileOf": OGC uses this to indicate a document is a profile of another.

4. "Implements": OGC uses this to indicate an encoding for conceptual model

5. "Complements"

6. "AlternativeFor": probably should be "AlternativeTo"?

Thoughts?

**Comment by nicholascar** [comment]
PROV-O's `wasInfluencedBy` is really a fall-back property (i.e. most generic) to be used when a known connection between things can't be expressed with anything more specific. It's not that different to `dcterms:relation` when it's used between things (as opposed to between temporal events and causative agents).

`wasDerivedFrom` is a PROV-O property with more specific definition: "A derivation is a transformation of an entity into another..." and there is also `wasRevisionOf`: "A revision is a derivation for which the resulting entity is a revised version of some original." and others.

**Comment by opoudjis** [comment]
I am again pasting here the list of current relaton relations, since the documentation they came from is not currently online:

Generic Relations:

translatedFrom:: document A is a translation of document B
hasTranslation:: document A has a translation as document B
includedIn:: document A is included in document B, through a well-defined relation outlined in <<host-item>>, and with distinct metadata
includes:: document A includes document B, through a well-defined relation outlined in <<host-item>>, and with distinct metadata
hasPart:: document A includes document B, with no distinct metadata
partOf:: document A is included in document B, with no distinct metadata
complements:: document A is a complement or supplement of document B
derivedFrom:: document A is derived from document B
instance:: document A is an instance of document B (e.g. an edition, a format, a single copy)
instanceOf:: document A has as an instance document B (e.g. an edition, a format, a single copy)
hasDraft:: document A has as a draft document B
draftOf:: document A is a draft of document B
updates:: document A updates document B
updatedBy:: document A is updated by document B
related:: document A is related to document B in an otherwise unspecified fashion
describes:: document A describes document B
describedBy:: document A is described by document B

Standards Relations:

obsoletes:: document A supersedes document B, and renders it obsolete
obsoletedBy:: document A is superseded by document B, and is rendered obsolete
supersedes:: document A supersedes document B, but is not rendered obsolete
supersededBy:: document A is superseded by document B, but is not rendered obsolete
adoptedFrom:: document A is adopted by a standards organisation from document B by a different organisation
identical:: document A is adopted from document B, without any change
equivalent:: document A is adopted from document B, without any significant textual change
nonequivalent:: document A is adopted from document B, and has been altered textually significantly
merges:: document A results from a merger of earlier documents B1, B2, B3...
splits:: document A is split off from earlier document B
corrects:: document A updates document B, and the change does not affect the intended meaning
correctedBy:: document A is updated by document B, and the change does not affect the intended meaning
amends:: document A updates document B, and the change is a minor change to the intended meaning
amendedBy:: document A is updated by document B, and the change is a minor change to the intended meaning
revised:: document A updates document B, and the change is a major change to the intended meaning
revisedBy:: document A is updated by document B, and the change is a major change to the intended meaning

**Comment by opoudjis** [comment]
> https://www.w3.org/TR/prov-o/ defines a relation called wasInfluencedBy which is being used in OGC. Should we have this?

As explained by @nicholascar, this is `related`
 
> "Uses": OGC uses the "uses" relation to indicate a document "refers" to another document. Should we have a "refers" relationship?

No objection. Refer also https://github.com/relaton/relaton-models/issues/23, dcterms:isReferencedBy

> "IsProfileOf": OGC uses this to indicate a document is a profile of another.

We currently have `derivedFrom`. I am very wary of introducing idiosyncratic relations into Relaton.

> "Implements": OGC uses this to indicate an encoding for conceptual model

This seems like a specialisation of dcterms:conformsTo. Again, I am very wary of introducing idiosyncratic relations into Relaton.

> "Complements"

`complements`

> "AlternativeFor": probably should be "AlternativeTo"?

What is this supposed to be? `equivalent`? `nonequivalent`? `instance`? Something else?

**Comment by opoudjis** [comment]
relations are currently encoded as

````
<relation type="X">
  <bibitem>(bibliographic entry)</bibitem>
  <locality>(portion of bibliographic entry relevant)</locality>
</relation>
````

For idiosyncratic relations, we can consider encoding the specific relation as a separate tag, while retaining the type attribute as the interoperable class of relation; just as we have done with contributor roles in Relaton.

````
<relation type="derivedFrom">
  <description>isProfileOf</description>
  <bibitem>(bibliographic entry)</bibitem>
  <locality>(portion of bibliographic entry relevant)</locality>
</relation>
````

But a parsimonious, generic repertoire of document relations is important to retain: we cannot have it turn into a miscellany of every document relation devised by every SDO there has been. If anything, we can probably cut down on the relations we currently do support.

**Comment by nicholascar** [comment]
I think a qualified relation patten would be good here: A relates to B with some term qualifying the relation and thus indicating the specific relation type. The list of all qualifying terms could be a stand-alone vocab.

**Comment by opoudjis** [comment]
So, this has to work with a preexisting bibliographic model, which we have rolled out to a dozen Standards bodies. If I understand you correctly, we already have the qualifying terms describing relations, as a controlled vocabulary (e.g. "derivedFrom"). 

I'm just saying that, rather than expand the generic controlled vocabulary to include relations specific to a standards body or class of documents, we refine it in a description term (which may or may not itself be a controlled vocabulary; but because our bibliographic model is generic, we'd prefer it not be.) So the generic controlled vocabulary remains "derived from", and the local refinement is "isProfileOf".

We're likely  agreeing here.

**Comment by ronaldtse** [comment]
My original point of posting this is to determine whether the OGC relations are "typical" enough to be included in the "generic" relationship controlled vocabulary. If they are considered too specific to OGC or are already covered by the existing relationships (which means we will do a OGC-specific mapping), then we're all good.

**Comment by opoudjis** [comment]
Everything but isProfileOf is covered by the existing relationships. I think isProfileOf is too specific for me to be comfortable coding it as a relationship, I would prefer to code it as "derived from" with a local refinement.

Implementing relation/description now.

**Comment by nicholascar** [comment]
I think it’s correct that the general `wasDerivedFrom` is indeed a super property of `isProfileOf`. (I’m one of the Profile Vocab editors!). 

All profiles derive from (potentially multiple) things that they profile with the additional axiom that things conforming to the profile conform to the thing profiled. This chained conformance is clearly not always the case for all things derived from other things - the general derived from case.

**Comment by opoudjis** [comment]
True enough, but subproperties can have additional attributes of their own...

**Comment by opoudjis** [comment]
@nicholascar @ronaldtse I will be proceeding to some rationalising of the relations list before I publish the documentation; the list is somewhat woolly, and I'm concerned that the basic list be more parsimonious. I propose:

* supersedes, corrects, amends, revises as a subproperty of obsoletes 
* hasPart as a subproperty of includes
* adoptedFrom, identical, equivalent, nonequivalent as a subproperty of derivedFrom

**Comment by nicholascar** [comment]
For the properties you propose, could you perhaps pick up these from well known OWL ontologies so future OWL translations would be eased: 

* supersedes: `dcterms:replaces`
* corrects: sub property of `dcterms:replaces`
* amends: ??
* revises as a subproperty of obsoletes: inv. of `prov:wasRevisionOf`
* hasPart as a subproperty of includes: `dcterms:hasPart`
* adoptedFrom: `prov:wasDerivedFrom` or sub property thereof
* identical: `owl:sameAs`
* nonequivalent as a subproperty of: derivedFrom: sub property of `prov:wasDerivedFrom`

**Comment by opoudjis** [comment]
We can't replace our terms with OWL terms; but we can point to these as equivalents. But I'm concerned that OWL and Dublin Core are not as detailed as the properties we are talking about...

**Comment by ronaldtse** [comment]
@nicholascar thanks for the suggestion! We can certainly map to these equivalents for interoperability. The purpose of those properties are slightly different from the semantic meanings we intend in this model so it would be more consistent keep this set separate.

I think we need further clarification of `identical` -- the standardized document notion of "identical" is that the content is identical in a "national adoption" -- not the document itself being an identical copy (an "identical" document can have a different cover, different document identifier, foreword, etc).

**Comment by opoudjis** [comment]
@andrew2net you will need to carry our the following refactoring of document relations:

````
<relation type="supersedes">
````

needs to be replaced by

````
<relation type="obsoletes">
<description>supersedes</description>
````

The same applies to `corrects`, `amends`, `revises`.

````
<relation type="supersededBy">
````

needs to be replaced by

````
<relation type="obsoletedBy">
<description>supersededBy</description>
````

The same applies to `correctedBy`, `amendedBy`, `revisedBy`.

````
<relation type="adoptedFrom">
````

needs to be replaced by

````
<relation type="derivedFrom">
<description>adoptedFrom</description>
````

The same applies to `identical`, `equivalent`, `nonequivalent`.

**Comment by opoudjis** [comment]
This ticket has turned into an implementation ticket, and soon will close. Further discussion should move to new ticket.

**Comment by opoudjis** [comment]
Will leave partOf alone; it's too enmeshed.

**Comment by opoudjis** [comment]
I am rethinking this, after discussion with Ronald. @andrew2net sorry, but he's right about things. Will update tomorrow.

**Comment by opoudjis** [comment]
identical, equivalent, nonequivalent become subclasses of adoptedFrom

**Comment by opoudjis** [comment]
supersedes is collapsed into obsoletes; the only distinction between them is the presence of a withdrawal date on the older document, that indicates a transition period

**Comment by opoudjis** [comment]
@andrew2net the previous two comments apply:

* identical, equivalent, nonequivalent become subclasses of adoptedFrom (so they are removed from list of types, and become descriptions)
* supersedes is collapsed into obsoletes; the only distinction between them is the presence of a withdrawal date on the older document, that indicates a transition period (so obsoletes is the relation type, and supersedes can be a description, but is preferably indicated only by the obsoleted date on the older bibitem.)

**Comment by opoudjis** [comment]
@andrew2net Can we close this issue?

**Comment by andrew2net** [comment]
@opoudjis the relations types are updated, so I think yes, we can close this issue.
