### ISSUE TITLE
Considering Dublin Core relationships

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#23]
What do we do with the relationships that exist in Dublin Core?

2.2.6 dcterms:conformsTo
2.2.13 dcterms:hasFormat
2.2.14 dcterms:hasPart
2.2.15 dcterms:hasVersion
2.2.17 dcterms:isFormatOf
2.2.18 dcterms:isPartOf
2.2.19 dcterms:isReferencedBy
2.2.20 dcterms:isReplacedBy
2.2.21 dcterms:isRequiredBy
2.2.22 dcterms:isVersionOf

https://www.dublincore.org/resources/userguide/publishing_metadata/#Properties_of_the_terms_namespace_used_only_with_non-literal_values

**Comment by nicholascar** [comment]
The critical one for the W3C *Profiles Vocabulary* is [dcterms:conformsTo](https://w3c.github.io/dx-prof/prof/#Property:conformsTo).

Also important one, but not listed above, is and [dcterms:format](https://w3c.github.io/dx-prof/prof/#Property:format). See [dcterms:hasFormat](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/hasFormat)'s definition: there can easily be confusion between `dcterms:format` & `dcterms:hasFormat`!

**Comment by opoudjis** [comment]
For reference (since there is no longer a public version of this), this is the current list of Relaton document relations:

Generic Relations:

translatedFrom:: document A is a translation of document B
hasTranslation:: document A has a translation as document B
includedIn:: document A is included in document B, through a well-defined relation outlined in <<host-item>>, and with distinct metadata
includes:: document A includes document B, through a well-defined relation outlined in <<host-item>>, and with distinct metadata
hasPart:: document A includes document B, with no distinct metadata
partOf:: document A is included in document B, with no distinct metadata
complements:: document A is a complement or supplement of document B
derivedFrom:: document A is derived from document B
instance:: document A is an instance of document B (e.g. an edition, a format, a single copy)
instanceOf:: document A has as an instance document B (e.g. an edition, a format, a single copy)
hasDraft:: document A has as a draft document B
draftOf:: document A is a draft of document B
updates:: document A updates document B
updatedBy:: document A is updated by document B
related:: document A is related to document B in an otherwise unspecified fashion
describes:: document A describes document B
describedBy:: document A is described by document B

Standards Relations:

obsoletes:: document A supersedes document B, and renders it obsolete
obsoletedBy:: document A is superseded by document B, and is rendered obsolete
supersedes:: document A supersedes document B, but is not rendered obsolete
supersededBy:: document A is superseded by document B, but is not rendered obsolete
adoptedFrom:: document A is adopted by a standards organisation from document B by a different organisation
identical:: document A is adopted from document B, without any change
equivalent:: document A is adopted from document B, without any significant textual change
nonequivalent:: document A is adopted from document B, and has been altered textually significantly
merges:: document A results from a merger of earlier documents B1, B2, B3...
splits:: document A is split off from earlier document B
corrects:: document A updates document B, and the change does not affect the intended meaning
correctedBy:: document A is updated by document B, and the change does not affect the intended meaning
amends:: document A updates document B, and the change is a minor change to the intended meaning
amendedBy:: document A is updated by document B, and the change is a minor change to the intended meaning
revised:: document A updates document B, and the change is a major change to the intended meaning
revisedBy:: document A is updated by document B, and the change is a major change to the intended meaning

**Comment by opoudjis** [comment]
Of the relations given above:

2.2.6 dcterms:conformsTo (not specified outside of "related")
2.2.12 dcterms:format: (not specified outside of "related"; instance is relation of Work and Format, we do not express relation of Format to Format)
2.2.13 dcterms:hasFormat : **instance** (less specific relation)
2.2.14 dcterms:hasPart : **hasPart**
2.2.15 dcterms:hasVersion : **instance** (less specific relation)
2.2.17 dcterms:isFormatOf : **instanceOf** (less specific relation)
2.2.18 dcterms:isPartOf : **partOf**
2.2.19 dcterms:isReferencedBy (not specified outside of "related")
2.2.20 dcterms:isReplacedBy : **obsoletedBy**
2.2.21 dcterms:isRequiredBy (not specified outside of "related"; adoptedFrom and derivedFrom are similar but not the same relation)
2.2.22 dcterms:isVersionOf : **instanceOf** (less specific relation)

Our model has focused to date on bibliographic relations of standards in particular, as Work to other Works or entities under Work; we haven't had reason to differentiate Formats and Expressions, or to relate Formats to each other.
