### ISSUE TITLE
Handle "combined" documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#26]
A standard document can often contain "combined" documents, such as:
* Document itself (is not combined)
* Document + supplement document(s) included (e.g. amendment, technical corrigendum), included means "provided as additional pages" but the original text is unchanged.
* Document + supplement document(s) applied, meaning that the changes are "applied" => original text is modified.

This applies to ISO, IEC, ITU and NIST documents.

(relevant to https://github.com/metanorma/metanorma-nist/issues/168)

e.g. For ISO documents, from RFC 5141:

```
   includedsuppl = "-" suppltype supplnumber [ "." supplversion ]

      An <isoversion> can be linked to a simpleversion by defining an
      existing simpleversion as baseversion and listing all the
      <supplement> elements (corrections and amendments) incorporated
      into that version.

      Examples for the <isoversion> (internal ISO version) scheme:

         1 = first version of standard

         1-amd1.v1 =  first version of standard incorporating first
         version of Amendment 1

         1-amd1.v1-amd2.v1 = first version of standard incorporating
         first version of Amendment 1 and first version of Amendment 2

         1-amd1.v2-amd2.v1-amd3 = first version of standard
         incorporating corrected version of Amendment 1, first version
         of Amendment 2, and highest version of Amendment 3

         1-cor3 = first version of standard incorporating highest
         version of Technical Corrigendum 3

         1-amd1-cor3 = first version of standard incorporating highest
         version of Amendment 1 and highest version of Technical
         Corrigendum 3
```

**Comment by ronaldtse** [comment]
Related to https://github.com/relaton/relaton-iec/issues/22 and relaton/relaton-iso#85

**Comment by opoudjis** [comment]
I assume that, if we have original document ISO 1, and Amendment Amd 1,

* Document + supplement document(s) included (e.g. amendment, technical corrigendum), included means "provided as additional pages" but the original text is unchanged.

This means:

`bibdata/docidentifier = "ISO 1 + Amd 1"`
`bibdata/relation[@type = "hasPart"]/bibitem[docidentifier = "ISO 1"]`
`bibdata/relation[@type = "hasPart"]/bibitem[docidentifier = "Amd 1"]`

* Document + supplement document(s) applied, meaning that the changes are "applied" => original text is modified.

This means:

`bibdata/docidentifier = "ISO 1, Amd 1"` ???
`bibdata/relation[@type = "updates"]/bibitem[docidentifier = "ISO 1"]`
`bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 1"]`

**Comment by ronaldtse** [comment]
> bibdata/docidentifier = "ISO 1 + Amd 1"
> bibdata/relation[@type = "hasPart"]/bibitem[docidentifier = "ISO 1"]
> bibdata/relation[@type = "hasPart"]/bibitem[docidentifier = "Amd 1"]

I don't think this works. What if the document is "ISO 1-2" (part 2)? The "part" meaning of a "document part" and generic "a part of" needs to be distinguished.

The latter is like saying the document has a "part" of "foreword".

**Comment by ronaldtse** [comment]
Maybe the other way around works better?
"+" means incorporated
", " means included separately

"ISO 1-2 + Amd 1"
vs
"ISO 1-2, Amd 1"

More samples from IEC we should handle:
* IEC 60601-2-63:2012/Amendment 1:2017
  * => single amendment itself
* Consolidation of IEC 60027-1:1992, its Amendment 1:1997 and its Amendment 2:2005
  * IEC 60027-1, Amd 1, Amd 2
* Corrigendum 1:2001 to Amendment 2:1994 to IEC 60068-2-2:1976
  * IEC 60068-2-2:1976/Amd 2:1994/Cor 1:2001
* Consolidation of amendment 1:1993 with IEC 60068-2-2:1974
  * IEC 60068-2-2:1974, Amd 1:1993

**Comment by opoudjis** [comment]
I don't know where to take it from here, Ronald. You're not coming up with a better model.

> What if the document is "ISO 1-2" (part 2)? The "part" meaning of a "document part" and generic "a part of" needs to be distinguished.

ISO 1-2 is a part of ISO-1
ISO 1-2 is a part of (ISO 1-2 + Amd1)

I see no problem with that. And hasPart should be interpreted generically; it is if anything more ad hoc than includes. At most, refine the description of the relation to be "compilation" or "ad hoc" or "with corrections", as opposed to "original publication".

> The latter is like saying the document has a "part" of "foreword".

If Amd1 has been published separately, it isn't. If not, fine, drop that relation.

**Comment by opoudjis** [comment]
ok, let me try this again:

"ISO 1-2, Amd 1"

i.e. ISO 1-2 and Amd 1 exist as separate publications, and are bundled together for this publication, original text unchanged:

bibdata/docidentifier = "ISO 1 + Amd 1"
bibdata/relation[@type = "hasPart"][description = "compilation"]/bibitem[docidentifier = "ISO 1"]
bibdata/relation[@type = "hasPart"][description = "compilation"]/bibitem[docidentifier = "Amd 1"]

"ISO 1-2 + Amd 1"

i.e. the changes in Amd 1 have been applied to ISO 1-2, this is updated text.

bibdata/relation[@type = "updates"]/bibitem[docidentifier = "ISO 1"]
bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 1"] (only if Amd 1 has been published separately)

IEC 60601-2-63:2012/Amendment 1:2017
=> single amendment itself

bibdata/relation[@type = "complements"][description = "changes log"]/bibitem[docidentifier = "IEC 60601-2-63:2012"] (it is an update, but can't be read in isolation from the original)

It's not actually an update by our definition, because it is not a new edition of the original.

Consolidation of IEC 60027-1:1992, its Amendment 1:1997 and its Amendment 2:2005
IEC 60027-1, Amd 1, Amd 2

bibdata/relation[@type = "updates"]/bibitem[docidentifier = "IEC 60027-1"]
bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 1"]
bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 2"]

Corrigendum 1:2001 to Amendment 2:1994 to IEC 60068-2-2:1976
IEC 60068-2-2:1976/Amd 2:1994/Cor 1:2001

bibdata/relation[@type = "complements"][description = "correction"]/bibitem[docidentifier = "Amd2"]/relation[@type = "complements"][description = "changes log"]/bibitem[docidentifier = "IEC 60068-2-2:1976"]

Corrigenda are not new editions of the amendments, they are patches, and patches are complements. So This is a complement of a complement.

Consolidation of amendment 1:1993 with IEC 60068-2-2:1974
IEC 60068-2-2:1974, Amd 1:1993

bibdata/relation[@type = "updates"]/bibitem[docidentifier = "IEC 60068-2-2:1974"]
bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 1"]

So the critical distinction in all of these is:

* Is the source document the basis for the new document?  If so, there is an update relationship. If not, and the new document is some sort of patch, then it is a complement: it is not a new edition. (I want to insist on that; there will be massive confusion otherwise.)

* Is the source document included unchanged in the new document? If so, there is a partOf relationship, whether or not they are named Part I, Part II, and whether or not the additions are subsequent to the new document.

* Is the source document present and changed in the new document? Then there is an updates relation

* Are the amendments applied to the source document? Then there is a derivedFrom relation.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis is the point to handle references like "ISO 1-2, Amd 1" and "ISO 1-2 + Amd 1"?

**Comment by ronaldtse** [comment]
Most of them look good.

> IEC 60601-2-63:2012/Amendment 1:2017
> => single amendment itself
> 
> bibdata/relation[@type = "complements"][description = "changes log"]/bibitem[docidentifier = "IEC 60601-2-63:2012"] (it is an update, but can't be read in isolation from the original)
> 
> It's not actually an update by our definition, because it is not a new edition of the original.

I don't think we should name this "changes log" because this is clearly not a change log. We should just call this an "amendment" -- everyone in the standards world understands what an "amendment" is.

> Consolidation of IEC 60027-1:1992, its Amendment 1:1997 and its Amendment 2:2005
> IEC 60027-1, Amd 1, Amd 2
> 
> bibdata/relation[@type = "updates"]/bibitem[docidentifier = "IEC 60027-1"]
> bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 1"]
> bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 2"]

This is very odd. Here are we have 3 separate items, they are 3 different documents. The bibdata represents not 1 document, but 1 collection with 3 documents.

This should be represented as 1 collection bibdata with 3 different document bibdata within the collection bibdata.

> Corrigendum 1:2001 to Amendment 2:1994 to IEC 60068-2-2:1976
> IEC 60068-2-2:1976/Amd 2:1994/Cor 1:2001
> 
> bibdata/relation[@type = "complements"][description = "correction"]/bibitem[docidentifier = "Amd2"]/relation[@type = "complements"][description = "changes log"]/bibitem[docidentifier = "IEC 60068-2-2:1976"]
> 
> Corrigenda are not new editions of the amendments, they are patches, and patches are complements. So This is a complement of a complement.

Again, an "amendment" is clearly not a "changes log", it is a document by itself.

In the standards world, an "amendment" is a content change -- a "correction" is a minor change that does not affect the base document's meaning.

> Consolidation of amendment 1:1993 with IEC 60068-2-2:1974
> IEC 60068-2-2:1974, Amd 1:1993
> 
> bibdata/relation[@type = "updates"]/bibitem[docidentifier = "IEC 60068-2-2:1974"]
> bibdata/relation[@type = "derivedFrom"]/bibitem[docidentifier = "Amd 1"]

This is a collection of two separate documents, even though these two documents are related.

> So the critical distinction in all of these is:
> 
> * Is the source document the basis for the new document?  If so, there is an update relationship. If not, and the new document is some sort of patch, then it is a complement: it is not a new edition. (I want to insist on that; there will be massive confusion otherwise.)
> * Is the source document included unchanged in the new document? If so, there is a partOf relationship, whether or not they are named Part I, Part II, and whether or not the additions are subsequent to the new document.
> * Is the source document present and changed in the new document? Then there is an updates relation
> * Are the amendments applied to the source document? Then there is a derivedFrom relation.

All of these describe relationships -- indeed, the relationships should be added. But the key point is if it is a collection, represent it as a collection. The relationships can be made within the document bibdata inside the collection.

**Comment by ronaldtse** [comment]
> is the point to handle references like "ISO 1-2, Amd 1" and "ISO 1-2 + Amd 1"?

@andrew2net yes, this is also for mapping with RFC 5141.

**Comment by andrew2net** [comment]
> All of these describe relationships -- indeed, the relationships should be added. But the key point is if it is a collection, represent it as a collection. The relationships can be made within the document bibdata inside the collection.

@ronaldtse ISO, IEC, ITU, and NIST return a single document. Collections are handled by relaton-cli. Do we need to make the ISO, IEC, ITU, and NIST return collection?
In which case we should return a collection and in which return a document with relation?

PS Maybe we should put the functionality to the `relaton` gem. What do you think?

**Comment by ronaldtse** [comment]
> ISO, IEC, ITU, and NIST return a single document. Collections are handled by relaton-cli. Do we need to make the ISO, IEC, ITU, and NIST return collection?

ISO, ITU and NIST are single documents, so this does not apply directly in scraping. However, we need to be able to support it when we build the bibliographic item manually (e.g. in a Metanorma collection).

There is one case in IEC for scraping -- the IEC 60050 documents are sold in "collections". 

> PS Maybe we should put the functionality to the relaton gem. What do you think?

Agree!
