### ISSUE TITLE
Update relation types

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-models#27]
The list of relation types needs to be updated according to #22.

**Comment by andrew2net** [comment]
I thought the description's aim is reducing the relation types list. Why do we need the description?

**Comment by opoudjis** [comment]
... We do, and I'm still using the description to not add corrects, amends, revises, identical, equivalent, nonequivalent, facsimile, replica.

There are still a lot more relations than there were before, because I've broadened the scope of the relations to encompass everything in bibliographies, and not just standards-specific concerns, as relaton is meant to be a generic bibliographic tool.
