### ISSUE TITLE
BIbitem model: why is `formattedref` and `title` considered exclusive?

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#37]
https://github.com/relaton/relaton-models/blob/ec12a0b5f00fd9e5dd19a63e6d0e1658d0165331/models/BibliographicItem.lutaml#L28

Why?

**Comment by opoudjis** [comment]
I know why I originally did it—because if you have a formatted ref, everything else, including the title, is redundant: I didn't want two different sources of truth in the grammar. But that's overscrupulous (and is being ignored in the Presentation XML); I'll get rid of it.

**Comment by opoudjis** [comment]
@andrew2net Formatted ref was mutually exclusive with title, because it was originally only intended for rendering, and I didn't want two different sources of truth in the grammar for rendering. But we are retaining semantic information in bibitem during processing, so I'm no longer doing so.

formattedref is intended for rendering and only for rendering; any semantic information in bibitem should use other fields. I've been lazy about using formattedref for relations in particular; we need to stop doing that...
