### ISSUE TITLE
Make `Role.type`, and possibly `ContributionInfo.role`, required

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-models#45]
As discussed—if nothing is required on `Role`, then an empty object is a valid role (which it probably shouldn’t be). Also, Nick stated that a contributor without a role also doesn’t make sense, so we could probably make role on contribution info required as well…

**Comment by opoudjis** [comment]
@ronaldtse I'm ok to strengthen `role` and `role/@type` to both be mandatory on contributors in our grammar, with the rationale that this grammar is intended for well-curated data, in which all contributors' relation to the bibliographic work is well-understood—rather than the initial laxity of the schema, which was meant to cope with whatever bibliographic data it could find, and would tolerate underdefined contributors.
